### PR TITLE
Expanding artifactory_helpers for JWST and beyond

### LINKED ISSUE #9: Move compare output function over
A helper function to compare FITS and/or ASCII files. The ASCII diff can probably be simplified a little by using https://astropy.readthedocs.io/en/latest/table/operations.html#table-diff .

https://github.com/spacetelescope/drizzlepac/blob/f5899e8110f565d1bd28b78571f314b88e50af9f/tests/resources.py#L248-L266

cc @stsci-hack and @SaOgaz

### LINKED ISSUE #10: Move new truth upload function over
https://github.com/spacetelescope/drizzlepac/blob/f5899e8110f565d1bd28b78571f314b88e50af9f/tests/resources.py#L282-L292

Perhaps add:

* Option to opt-in only for given run. Opt-out by default.
* Option to rename in such a way that local comparison between output and truth in the working directory is still possible.

cc @stsci-hack and @SaOgaz

### LINKED ISSUE #17: TST: Enable nightly run
Maybe wait till Astropy 3.1 is out. Then, we can do this in conjunction with adding extra run for stable Astropy over at `Jenkinsfile`.

### PR DESCRIPTION
**Pull request by pllim**
I am building on top of @stsci-hack 's work over at #14, including clean-ups, bug fixes, and adding tests. cc @jdavies-st

Fix #9 
Fix #10 
Fix #17 
Close #14 
Partially address #6

### CODE REVIEW

**Comment by pllim** [comment]
This warning in test log bugs me but does not affect the results.

```
<unknown>:317: DeprecationWarning: invalid escape sequence \g
```

**Comment by jdavies-st** [comment]
That warning is probably from the REGEX not getting passed a raw string.  Instead of `'\g'` it should be `r'\g'`.  I think.

**Comment by pllim** [comment]
Correct. But I can't figure out where it is. I can't find it in this repo.

**Comment by pllim** [comment]
Ohh the docstring! :bulb:

**Comment by pllim** [comment]
This does not seem to break existing tests over at `hstcal`, `acstools`, or `costools`. I have approval from @jdavies-st offline to merge, so merging!

**Pull request merged**
