### PR TITLE
test with dev builds of Numpy and scipy

### PR DESCRIPTION
**Pull request by zacharyburnett**
Resolves [SCSB-88](https://jira.stsci.edu/browse/SCSB-88)

### CODE REVIEW

**Review by nden — APPROVED** [review]

**Comment by pllim** [comment]
I don't think it works:

https://github.com/spacetelescope/ci_watson/actions/runs/6164337508/job/16729844826?pr=57

**Review by nden — CHANGES_REQUESTED** [review]
you are right, it didn't pick up numpy dev

**Comment by pllim** [comment]
I added a commit that fixed it. 

I don't like adding special requirements file though. Why not use tox? Anyway, I think this is ok now if you just want to accept this patch.

**Comment by zacharyburnett** [comment]
> I added a commit that fixed it.
> 
> I don't like adding special requirements file though. Why not use tox? Anyway, I think this is ok now if you just want to accept this patch.

I can definitely do that, but it might be too much for this PR. I'll merge this and make another one for `tox`

**Pull request merged**
